# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
services:
    app.form.registration:
        class: AppBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }
